### ISSUE TITLE
`Text styled with px unit` error thrown incorrectly

### ISSUE THREAD

**Issue by ChrisBAshton** [bbc/bbc-a11y#246]
## Summary

I'm getting a _lot_ of errors like this, and I'm not sure that they're valid...?:

`    - Text styled with px unit: /html/body/span/p[1]`

My `p` CSS is as follows:

```css
p {
    font-size: 1.125rem;
    font-weight: 200;
    line-height: 1.8;
}
```

The `px` value comes from the `body`:

```css
html {
    box-sizing: border-box;
    margin: 0;
    padding: 0;
    background: #D4E7EE;
    font: normal 16px Helvetica, Arial, sans-serif;
    line-height: 1.2;
    color: #000000;
    background-color: white;
}
```

I would expect no errors as I've set the font size with `rem`, and that it shouldn't be a problem that I've set a default base font size of `16px` on the `html` element. Am I missing something?

I'm testing one of my side project sites: https://studentmunch.com/

Thanks
